telegram:
  token: your_token

buttons_per_row: 3

conversations:
  timeout: 1200

view_transactions:
  count_transactions_in_list: 10

jobs:
  results_time: '20:00:00'
  backup_database: '20:00:00'

admin_list: [] # telegram_user_id

logging:
  version: 1
  disable_existing_loggers: false

  formatters:
    standard:
      format: '%(levelname)-10s | %(asctime)-25s | %(name)s | %(filename)s/%(funcName)s:%(lineno)s | %(message)s'
  handlers:
    'null':
      class: logging.NullHandler

    default:
      level: INFO
      formatter: standard
      class: logging.StreamHandler
      stream: ext://sys.stderr

    file:
      level: DEBUG
      formatter: standard
      class: logging.handlers.RotatingFileHandler
      filename: ./Logs/log.txt
      maxBytes: 500000
      backupCount: 1000

  loggers:
    mkbot:
      handlers: [default, file]
      level: DEBUG

  root:
    handlers: ['null']
