
class States:
    TO_CHOOSE_EARNING_OR_CONSUMPTION, TO_MENU_MANAGE_CATEGORIES, TO_ADD_CATEGORY, \
        TO_CONFIRM_ADD_CATEGORY, TO_DELETE_CATEGORY, TO_CONFIRM_DELETE_CATEGORY, \
        TO_CONFIRM_SET_DEFAULT_CATEGORIES, TO_EDIT_CATEGORY, TO_WRITE_NEW_CATEGORY, \
        TO_CONFIRM_EDIT_CATEGORY = range(10)
