class States:
    TO_MAIN_MENU, TO_CHOOSE_ADD_TYPE_LIMIT, TO_CHOOSE_ADD_CATEGORY_LIMIT, \
    TO_ADD_WRITE_AMOUNT_MONEY, TO_CHOOSE_EDIT_LIMIT, TO_CHOOSE_EDIT_ACTION, TO_EDIT_TYPE, \
    TO_EDIT_CATEGORY, TO_EDIT_WRITE_MONEY= range(9)
